[package]
name = "dyn_struct"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
hassle-rs = "0.11.0"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive"] }
fxhash = "0.2.1"
dyn_struct_derive = { path = "dyn_struct_derive" }

# TODO move to dev-dependencies?
glam = { version = "0.27.0", features = ["bytemuck"] }
spirq = "1.2.2"

[profile.release-with-debug]
inherits = "release"
debug = true
