[package]
name = "dyn_struct_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive"] }
fxhash = "0.2.1"
glam = { version = "0.27.0", features = ["bytemuck"] }
dyn_struct_derive = { path = "../dyn_struct_derive" }
