[package]
name = "dyn_struct_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
proc-macro-crate = "1.2"


[lib]
proc-macro = true
