[package]
name = "dyn_struct_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive"] }
indexmap = "2.6.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
proc-macro-crate = "1.2"

dyn_struct_core = { path = "../dyn_struct_core" }

[lib]
proc-macro = true
